FileVersion = 1

[Project]
Name = "cglm-beef"
TargetType = "BeefLib"
StartupObject = "cglm.Program"
DefaultNamespace = "cglm"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\cglm.lib"]
