FileVersion = 1

[Project]
Name = "cglm-beef"
TargetType = "BeefLib"
StartupObject = "cglm.Program"
DefaultNamespace = "cglm"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\cglm_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\cglm.lib"]
